feat: calculate virtual elements for CDS Views
DevEpos/abap-db-browser pull request #13
Opened 2021-03-21 16:07 UTC by reichr-dev

2021-03-21 16:08 UTC, reichr-dev commented
Resolves Issue #12

2021-03-22 10:50 UTC, stockbal requested changes
I guess all in all. The coding assumes that there is only one calculated field in the view. Then it would work

2021-03-22 10:50 UTC, stockbal commented on src/ui/util/zcl_dbbr_cds_selection_util.clas.abap
> +            cx_sadl_exit.
the exception `cx_sadl_exit` does not exist in v7.50 so I gues we have to use `cx_root` in this case to also catch any exception that happen in the `calculate` call

2021-03-22 10:50 UTC, stockbal commented on src/ui/util/zcl_dbbr_cds_selection_util.clas.abap
> +    ENDLOOP.
I am not quite sure how the `SADL` engine is handling this, but wouldn't it be better to group the calculcation by exit-class?

Example:
```ABAP
...
@ObjectModel.virtualElementCalculatedBy: 'ABAP:CL_EXIT'
cast( '' as ztype ) as VirtualField1,

@ObjectModel.virtualElementCalculatedBy: 'ABAP:CL_EXIT'
cast( '' as ztype2 ) as VirtualField2,

@ObjectModel.virtualElementCalculatedBy: 'ABAP:CL_EXIT2'
cast( '' as ztype3 ) as VirtualField3,
...
```
So in this example there would be one call to `CL_EXIT` where the fields `VirtualField1` and `VirtualField2` are filled and one call to `CL_EXIT2` where the field `VirtualField3` is filled

2021-03-22 10:50 UTC, stockbal commented on src/ui/util/zcl_dbbr_cds_selection_util.clas.abap
> +          ASSIGN lr_t_calc_data->* TO <lt_calculated_data>.
Wouldn't this automatically override the calculated data from the previous iteration?

2021-03-25 14:13 UTC, closed without merging